### ISSUE TITLE
How to change the language applacation

### ISSUE THREAD

**Issue by popcorn2024ok** [strumok-app/strumok#1]
How to change the language in the application in English and Spanish is in Russian

**Comment by Andro999b** [comment]
Its in Ukrainian. Almost all content suppliers in app in Ukrainian language. Expect couple like hianime, anitaku, tmdb(that is half broken currently) and manga dex (that is actually multi lang). I am planning to add lang switcher Env <-> Urk and some more suppliers in eng for manga and movies. But its not a priority for now.
