### ISSUE TITLE
Video playback  error

### ISSUE THREAD

**Issue by popcorn2024ok** [strumok-app/strumok#3]
![20241125_220824](https://github.com/user-attachments/assets/79b6fda0-49b3-4ea5-ad64-21292db08eb5)

I have problems playing movies and series

I get this message video playback error

Version android mobile  and version android tv applications Strumok

**Comment by Andro999b** [comment]
This usually means that no video sources found. It's kinda regular staff for the TMDB because I haven't updated this supplier for a long time and 2 of 3 extractors a broken for now.

**Comment by Andro999b** [comment]
You can easily verify this by clicking on [source select icon](https://fonts.google.com/icons?selected=Material+Symbols+Outlined:track_changes:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=track&icon.size=24&icon.color=%235f6368) and observe empty sources lists.

**Comment by popcorn2024ok** [comment]
> This usually means that no video sources found. It's kinda regular staff for the TMDB because I haven't updated this supplier for a long time and 2 of 3 extractors a broken for now.

open a solution with
the tmdb api so that it works at 100% friend movies and series

**Comment by Andro999b** [comment]
I am going back to TMDB when done with my current priorities lists.
